add test apimain

diff --git a/Dockerfile.prod.local b/Dockerfile.prod.local
--- a/Dockerfile.prod.local
+++ b/Dockerfile.prod.local
@@ -36,9 +36,6 @@ WORKDIR /app
 
 RUN apk add --no-cache tzdata file
 
-RUN ls -la /app/release/ && \
-    test -f /app/release/apimain || (echo "apimain not found!" && exit 1)
-
 # Copy backend
 COPY --from=builder-backend /app/release /app/
 # Копируем конфиги и ресурсы
@@ -46,6 +43,7 @@ COPY --from=builder-backend /app/conf /app/conf/
 COPY --from=builder-backend /app/docs /app/docs/
 COPY --from=builder-backend /app/resources /app/resources/
 
+RUN ls -la /app/ && test -f /app/apimain && echo "✅ apimain found!" || (echo "❌ apimain not found!" && exit 1)
 
 RUN mkdir -p /app/runtime && chmod 777 /app/runtime
 
